import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gothamBook = localFont({
  src: "../fonts/GothamSSm-Book.otf",
  variable: "--font-gotham",
});

const gothamMedium = localFont({
  src: "../fonts/GothamSSm-Medium.otf",
  variable: "--font-gotham-medium",
});

const gothamBold = localFont({
  src: "../fonts/GothamSSm-Bold.otf",
  variable: "--font-gotham-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothamBook.variable} ${gothamMedium.variable} ${gothamBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
